// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package template

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgSaveReq struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ToUid                uint64   `protobuf:"varint,2,opt,name=ToUid,proto3" json:"ToUid,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	Status               bool     `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSaveReq) Reset()         { *m = MsgSaveReq{} }
func (m *MsgSaveReq) String() string { return proto.CompactTextString(m) }
func (*MsgSaveReq) ProtoMessage()    {}
func (*MsgSaveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *MsgSaveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSaveReq.Unmarshal(m, b)
}
func (m *MsgSaveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSaveReq.Marshal(b, m, deterministic)
}
func (m *MsgSaveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSaveReq.Merge(m, src)
}
func (m *MsgSaveReq) XXX_Size() int {
	return xxx_messageInfo_MsgSaveReq.Size(m)
}
func (m *MsgSaveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSaveReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSaveReq proto.InternalMessageInfo

func (m *MsgSaveReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MsgSaveReq) GetToUid() uint64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *MsgSaveReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MsgSaveReq) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Rsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rsp) Reset()         { *m = Rsp{} }
func (m *Rsp) String() string { return proto.CompactTextString(m) }
func (*Rsp) ProtoMessage()    {}
func (*Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rsp.Unmarshal(m, b)
}
func (m *Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rsp.Marshal(b, m, deterministic)
}
func (m *Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rsp.Merge(m, src)
}
func (m *Rsp) XXX_Size() int {
	return xxx_messageInfo_Rsp.Size(m)
}
func (m *Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_Rsp proto.InternalMessageInfo

func (m *Rsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Rsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type MsgListReq struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ToUid                uint64   `protobuf:"varint,2,opt,name=ToUid,proto3" json:"ToUid,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize             int64    `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgListReq) Reset()         { *m = MsgListReq{} }
func (m *MsgListReq) String() string { return proto.CompactTextString(m) }
func (*MsgListReq) ProtoMessage()    {}
func (*MsgListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *MsgListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgListReq.Unmarshal(m, b)
}
func (m *MsgListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgListReq.Marshal(b, m, deterministic)
}
func (m *MsgListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgListReq.Merge(m, src)
}
func (m *MsgListReq) XXX_Size() int {
	return xxx_messageInfo_MsgListReq.Size(m)
}
func (m *MsgListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgListReq.DiscardUnknown(m)
}

var xxx_messageInfo_MsgListReq proto.InternalMessageInfo

func (m *MsgListReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *MsgListReq) GetToUid() uint64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *MsgListReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *MsgListReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ChatMessage struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Uid                  uint64   `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ToUid                uint64   `protobuf:"varint,3,opt,name=ToUid,proto3" json:"ToUid,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
	Status               bool     `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChatMessage) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ChatMessage) GetToUid() uint64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatMessage) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type MsgListRsp struct {
	Msg                  []*ChatMessage `protobuf:"bytes,1,rep,name=Msg,proto3" json:"Msg,omitempty"`
	Total                int64          `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	Page                 int64          `protobuf:"varint,3,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize             int64          `protobuf:"varint,4,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	Code                 int64          `protobuf:"varint,5,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string         `protobuf:"bytes,6,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MsgListRsp) Reset()         { *m = MsgListRsp{} }
func (m *MsgListRsp) String() string { return proto.CompactTextString(m) }
func (*MsgListRsp) ProtoMessage()    {}
func (*MsgListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *MsgListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgListRsp.Unmarshal(m, b)
}
func (m *MsgListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgListRsp.Marshal(b, m, deterministic)
}
func (m *MsgListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgListRsp.Merge(m, src)
}
func (m *MsgListRsp) XXX_Size() int {
	return xxx_messageInfo_MsgListRsp.Size(m)
}
func (m *MsgListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_MsgListRsp proto.InternalMessageInfo

func (m *MsgListRsp) GetMsg() []*ChatMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *MsgListRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MsgListRsp) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *MsgListRsp) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *MsgListRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *MsgListRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ChatHistoryReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatHistoryReq) Reset()         { *m = ChatHistoryReq{} }
func (m *ChatHistoryReq) String() string { return proto.CompactTextString(m) }
func (*ChatHistoryReq) ProtoMessage()    {}
func (*ChatHistoryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *ChatHistoryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatHistoryReq.Unmarshal(m, b)
}
func (m *ChatHistoryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatHistoryReq.Marshal(b, m, deterministic)
}
func (m *ChatHistoryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatHistoryReq.Merge(m, src)
}
func (m *ChatHistoryReq) XXX_Size() int {
	return xxx_messageInfo_ChatHistoryReq.Size(m)
}
func (m *ChatHistoryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatHistoryReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatHistoryReq proto.InternalMessageInfo

func (m *ChatHistoryReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ChatUser struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=Account,proto3" json:"Account,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Status               bool     `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatUser) Reset()         { *m = ChatUser{} }
func (m *ChatUser) String() string { return proto.CompactTextString(m) }
func (*ChatUser) ProtoMessage()    {}
func (*ChatUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *ChatUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatUser.Unmarshal(m, b)
}
func (m *ChatUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatUser.Marshal(b, m, deterministic)
}
func (m *ChatUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatUser.Merge(m, src)
}
func (m *ChatUser) XXX_Size() int {
	return xxx_messageInfo_ChatUser.Size(m)
}
func (m *ChatUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatUser.DiscardUnknown(m)
}

var xxx_messageInfo_ChatUser proto.InternalMessageInfo

func (m *ChatUser) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChatUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatUser) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ChatUser) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *ChatUser) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type ChatHistoryRsp struct {
	Code                 int64       `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	User                 []*ChatUser `protobuf:"bytes,3,rep,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChatHistoryRsp) Reset()         { *m = ChatHistoryRsp{} }
func (m *ChatHistoryRsp) String() string { return proto.CompactTextString(m) }
func (*ChatHistoryRsp) ProtoMessage()    {}
func (*ChatHistoryRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *ChatHistoryRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatHistoryRsp.Unmarshal(m, b)
}
func (m *ChatHistoryRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatHistoryRsp.Marshal(b, m, deterministic)
}
func (m *ChatHistoryRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatHistoryRsp.Merge(m, src)
}
func (m *ChatHistoryRsp) XXX_Size() int {
	return xxx_messageInfo_ChatHistoryRsp.Size(m)
}
func (m *ChatHistoryRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatHistoryRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChatHistoryRsp proto.InternalMessageInfo

func (m *ChatHistoryRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ChatHistoryRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatHistoryRsp) GetUser() []*ChatUser {
	if m != nil {
		return m.User
	}
	return nil
}

type ChatNumberReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatNumberReq) Reset()         { *m = ChatNumberReq{} }
func (m *ChatNumberReq) String() string { return proto.CompactTextString(m) }
func (*ChatNumberReq) ProtoMessage()    {}
func (*ChatNumberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{8}
}

func (m *ChatNumberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatNumberReq.Unmarshal(m, b)
}
func (m *ChatNumberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatNumberReq.Marshal(b, m, deterministic)
}
func (m *ChatNumberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatNumberReq.Merge(m, src)
}
func (m *ChatNumberReq) XXX_Size() int {
	return xxx_messageInfo_ChatNumberReq.Size(m)
}
func (m *ChatNumberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatNumberReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChatNumberReq proto.InternalMessageInfo

func (m *ChatNumberReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ChatNumberRsp struct {
	Code                 int64    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	Number               int64    `protobuf:"varint,3,opt,name=Number,proto3" json:"Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatNumberRsp) Reset()         { *m = ChatNumberRsp{} }
func (m *ChatNumberRsp) String() string { return proto.CompactTextString(m) }
func (*ChatNumberRsp) ProtoMessage()    {}
func (*ChatNumberRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{9}
}

func (m *ChatNumberRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatNumberRsp.Unmarshal(m, b)
}
func (m *ChatNumberRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatNumberRsp.Marshal(b, m, deterministic)
}
func (m *ChatNumberRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatNumberRsp.Merge(m, src)
}
func (m *ChatNumberRsp) XXX_Size() int {
	return xxx_messageInfo_ChatNumberRsp.Size(m)
}
func (m *ChatNumberRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatNumberRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChatNumberRsp proto.InternalMessageInfo

func (m *ChatNumberRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ChatNumberRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ChatNumberRsp) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type CHSaveReq struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	ToUid                uint64   `protobuf:"varint,2,opt,name=ToUid,proto3" json:"ToUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CHSaveReq) Reset()         { *m = CHSaveReq{} }
func (m *CHSaveReq) String() string { return proto.CompactTextString(m) }
func (*CHSaveReq) ProtoMessage()    {}
func (*CHSaveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{10}
}

func (m *CHSaveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CHSaveReq.Unmarshal(m, b)
}
func (m *CHSaveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CHSaveReq.Marshal(b, m, deterministic)
}
func (m *CHSaveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CHSaveReq.Merge(m, src)
}
func (m *CHSaveReq) XXX_Size() int {
	return xxx_messageInfo_CHSaveReq.Size(m)
}
func (m *CHSaveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CHSaveReq.DiscardUnknown(m)
}

var xxx_messageInfo_CHSaveReq proto.InternalMessageInfo

func (m *CHSaveReq) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CHSaveReq) GetToUid() uint64 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgSaveReq)(nil), "template.MsgSaveReq")
	proto.RegisterType((*Rsp)(nil), "template.Rsp")
	proto.RegisterType((*MsgListReq)(nil), "template.MsgListReq")
	proto.RegisterType((*ChatMessage)(nil), "template.ChatMessage")
	proto.RegisterType((*MsgListRsp)(nil), "template.MsgListRsp")
	proto.RegisterType((*ChatHistoryReq)(nil), "template.ChatHistoryReq")
	proto.RegisterType((*ChatUser)(nil), "template.ChatUser")
	proto.RegisterType((*ChatHistoryRsp)(nil), "template.ChatHistoryRsp")
	proto.RegisterType((*ChatNumberReq)(nil), "template.ChatNumberReq")
	proto.RegisterType((*ChatNumberRsp)(nil), "template.ChatNumberRsp")
	proto.RegisterType((*CHSaveReq)(nil), "template.CHSaveReq")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x8f, 0xda, 0x30,
	0x10, 0x55, 0x62, 0x43, 0xd9, 0x41, 0xbb, 0xad, 0xa6, 0xdb, 0x6d, 0x94, 0x4b, 0xa3, 0x1c, 0x5a,
	0x4e, 0x1c, 0x40, 0x3d, 0xf4, 0x52, 0x69, 0x85, 0x2a, 0xb1, 0x52, 0x59, 0x55, 0xa6, 0xfc, 0x00,
	0x2f, 0xf1, 0xb2, 0x48, 0x4b, 0x93, 0xc6, 0x66, 0xfb, 0xf1, 0x8f, 0x7a, 0xee, 0x1f, 0x5c, 0x8d,
	0x71, 0x08, 0x46, 0xe1, 0x90, 0x53, 0xfc, 0x66, 0xc6, 0x9e, 0x37, 0xef, 0xd9, 0x01, 0x58, 0x3e,
	0x48, 0x33, 0x2c, 0xca, 0xdc, 0xe4, 0xd8, 0x33, 0x6a, 0x53, 0x3c, 0x4a, 0xa3, 0xd2, 0x7b, 0x80,
	0x99, 0x5e, 0xcd, 0xe5, 0x93, 0x12, 0xea, 0x27, 0xbe, 0x02, 0xb6, 0x58, 0x67, 0x51, 0x90, 0x04,
	0x03, 0x2e, 0x68, 0x89, 0x97, 0xd0, 0xf9, 0x9e, 0x53, 0x2c, 0xb4, 0xb1, 0x1d, 0xc0, 0x08, 0x5e,
	0xcc, 0x94, 0xd6, 0x72, 0xa5, 0x22, 0x96, 0x04, 0x83, 0x33, 0x51, 0x41, 0xbc, 0x82, 0xee, 0xdc,
	0x48, 0xb3, 0xd5, 0x11, 0x4f, 0x82, 0x41, 0x4f, 0x38, 0x94, 0x8e, 0x81, 0x09, 0x5d, 0x20, 0x02,
	0x9f, 0xe4, 0x99, 0xb2, 0x1d, 0x98, 0xb0, 0xeb, 0xc3, 0xc3, 0x42, 0xef, 0xb0, 0x34, 0xb3, 0xe4,
	0xbe, 0xae, 0xb5, 0x69, 0x43, 0x0e, 0x81, 0x7f, 0xab, 0x98, 0x31, 0x61, 0xd7, 0x18, 0x43, 0x8f,
	0xbe, 0xf3, 0xf5, 0x5f, 0x65, 0x89, 0x31, 0xb1, 0xc7, 0xe9, 0x2f, 0xe8, 0x4f, 0x1e, 0xa4, 0xa9,
	0x26, 0xb8, 0x80, 0xf0, 0x26, 0x73, 0x04, 0xc3, 0x9b, 0xac, 0x6a, 0x1b, 0x36, 0xb4, 0x65, 0x27,
	0x34, 0xe1, 0xa7, 0x34, 0xe9, 0x78, 0x9a, 0xfc, 0x0b, 0xea, 0xf9, 0x74, 0x81, 0x1f, 0x80, 0xcd,
	0xf4, 0x2a, 0x0a, 0x12, 0x36, 0xe8, 0x8f, 0xde, 0x0c, 0x2b, 0x8b, 0x86, 0x07, 0xe4, 0x04, 0x55,
	0xec, 0xfa, 0x1b, 0xf9, 0x68, 0x39, 0x31, 0xb1, 0x03, 0x6d, 0xc7, 0xde, 0x5b, 0xd1, 0x69, 0xb6,
	0xa2, 0xeb, 0x5b, 0x91, 0xc0, 0x05, 0xf1, 0x98, 0xae, 0xb5, 0xc9, 0xcb, 0x3f, 0x64, 0x47, 0xad,
	0x13, 0x27, 0x9d, 0xd2, 0xdf, 0xd0, 0xa3, 0x8a, 0x85, 0x56, 0xe5, 0x71, 0x8e, 0x7a, 0xdd, 0xca,
	0x4d, 0xe5, 0xaf, 0x5d, 0x53, 0xaf, 0xeb, 0xe5, 0x32, 0xdf, 0xfe, 0x30, 0xd5, 0x1d, 0x72, 0x90,
	0xf4, 0xba, 0x7e, 0x92, 0x46, 0x96, 0x4e, 0x48, 0x87, 0x4e, 0xea, 0x78, 0xef, 0x73, 0x6b, 0x7b,
	0xcd, 0xf0, 0x3d, 0x70, 0x62, 0x1d, 0x31, 0xab, 0x3c, 0xfa, 0xca, 0x53, 0x46, 0xd8, 0x7c, 0xfa,
	0x0e, 0xce, 0x29, 0x72, 0xbb, 0xdd, 0xdc, 0xa9, 0xb2, 0x49, 0x82, 0x85, 0x57, 0xd0, 0x9a, 0xc7,
	0x15, 0x74, 0x77, 0x5b, 0x9d, 0x87, 0x0e, 0xa5, 0x63, 0x38, 0x9b, 0x4c, 0x5b, 0x3e, 0xd1, 0xd1,
	0xff, 0x10, 0x38, 0x91, 0xc1, 0x11, 0xf4, 0x5d, 0x03, 0x3a, 0x02, 0x2f, 0xeb, 0xf1, 0xea, 0x87,
	0x1f, 0x9f, 0xd7, 0x51, 0xe2, 0xfd, 0x69, 0xbf, 0x87, 0x2e, 0xe7, 0xd1, 0x1e, 0xf7, 0x1e, 0xe3,
	0x86, 0xa8, 0x2e, 0xf0, 0x0b, 0xbc, 0x3c, 0x30, 0xc3, 0x6e, 0x8f, 0x7c, 0x45, 0xeb, 0x3b, 0x14,
	0x9f, 0xc8, 0xe8, 0x02, 0x3f, 0x03, 0xd4, 0x52, 0xe2, 0x5b, 0xbf, 0x6e, 0xef, 0x40, 0xdc, 0x9c,
	0xd0, 0x05, 0x7e, 0xf4, 0x68, 0xd8, 0xc9, 0x5f, 0x1f, 0xd4, 0x4e, 0x9b, 0x07, 0xbf, 0xeb, 0xda,
	0xff, 0xe3, 0xf8, 0x39, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x76, 0x72, 0xf6, 0x2d, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	MessageSave(ctx context.Context, in *MsgSaveReq, opts ...grpc.CallOption) (*Rsp, error)
	MessageList(ctx context.Context, in *MsgListReq, opts ...grpc.CallOption) (*MsgListRsp, error)
	ChatHistoryList(ctx context.Context, in *ChatHistoryReq, opts ...grpc.CallOption) (*ChatHistoryRsp, error)
	ChatNumber(ctx context.Context, in *ChatNumberReq, opts ...grpc.CallOption) (*ChatNumberRsp, error)
	ChatHistorySave(ctx context.Context, in *CHSaveReq, opts ...grpc.CallOption) (*Rsp, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) MessageSave(ctx context.Context, in *MsgSaveReq, opts ...grpc.CallOption) (*Rsp, error) {
	out := new(Rsp)
	err := c.cc.Invoke(ctx, "/template.Chat/MessageSave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) MessageList(ctx context.Context, in *MsgListReq, opts ...grpc.CallOption) (*MsgListRsp, error) {
	out := new(MsgListRsp)
	err := c.cc.Invoke(ctx, "/template.Chat/MessageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatHistoryList(ctx context.Context, in *ChatHistoryReq, opts ...grpc.CallOption) (*ChatHistoryRsp, error) {
	out := new(ChatHistoryRsp)
	err := c.cc.Invoke(ctx, "/template.Chat/ChatHistoryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatNumber(ctx context.Context, in *ChatNumberReq, opts ...grpc.CallOption) (*ChatNumberRsp, error) {
	out := new(ChatNumberRsp)
	err := c.cc.Invoke(ctx, "/template.Chat/ChatNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatHistorySave(ctx context.Context, in *CHSaveReq, opts ...grpc.CallOption) (*Rsp, error) {
	out := new(Rsp)
	err := c.cc.Invoke(ctx, "/template.Chat/ChatHistorySave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	MessageSave(context.Context, *MsgSaveReq) (*Rsp, error)
	MessageList(context.Context, *MsgListReq) (*MsgListRsp, error)
	ChatHistoryList(context.Context, *ChatHistoryReq) (*ChatHistoryRsp, error)
	ChatNumber(context.Context, *ChatNumberReq) (*ChatNumberRsp, error)
	ChatHistorySave(context.Context, *CHSaveReq) (*Rsp, error)
}

// UnimplementedChatServer can be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (*UnimplementedChatServer) MessageSave(ctx context.Context, req *MsgSaveReq) (*Rsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageSave not implemented")
}
func (*UnimplementedChatServer) MessageList(ctx context.Context, req *MsgListReq) (*MsgListRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageList not implemented")
}
func (*UnimplementedChatServer) ChatHistoryList(ctx context.Context, req *ChatHistoryReq) (*ChatHistoryRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatHistoryList not implemented")
}
func (*UnimplementedChatServer) ChatNumber(ctx context.Context, req *ChatNumberReq) (*ChatNumberRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatNumber not implemented")
}
func (*UnimplementedChatServer) ChatHistorySave(ctx context.Context, req *CHSaveReq) (*Rsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatHistorySave not implemented")
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_MessageSave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).MessageSave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Chat/MessageSave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).MessageSave(ctx, req.(*MsgSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_MessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).MessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Chat/MessageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).MessageList(ctx, req.(*MsgListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatHistoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatHistoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Chat/ChatHistoryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatHistoryList(ctx, req.(*ChatHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatNumberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Chat/ChatNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatNumber(ctx, req.(*ChatNumberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatHistorySave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CHSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatHistorySave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/template.Chat/ChatHistorySave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatHistorySave(ctx, req.(*CHSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "template.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MessageSave",
			Handler:    _Chat_MessageSave_Handler,
		},
		{
			MethodName: "MessageList",
			Handler:    _Chat_MessageList_Handler,
		},
		{
			MethodName: "ChatHistoryList",
			Handler:    _Chat_ChatHistoryList_Handler,
		},
		{
			MethodName: "ChatNumber",
			Handler:    _Chat_ChatNumber_Handler,
		},
		{
			MethodName: "ChatHistorySave",
			Handler:    _Chat_ChatHistorySave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
