apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-svc
  namespace: default
  labels:
    app: chat-svc
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: chat-svc
  template:
    metadata:
      labels:
        app: chat-svc
    spec:
      containers:
      - name: chat-svc
        image: docker.io/dk251626910/ffl-chat-svc:latest
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 60003
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: chat-svc
  namespace: default
spec:
  ports:
    - port: 60003
  selector:
    app: chat-svc