Name: chat.rpc
ListenOn: 0.0.0.0:60003
Etcd:
  Hosts:
    - dev.ll:2379
  Key: chat.rpc
Datasource: root:123456@tcp(dev.ll:3306)/fireflyChat?charset=utf8mb4&parseTime=True&loc=Local
Cache:
  - Host: dev.ll:6379
UserSvc:
  Etcd:
    Hosts:
      - dev.ll:2379
    Key: user.rpc
Log:
  ServiceName: "chat-svc"
  Mode: "file"
  Path: "/var/log/filebeat/chat-svc"
  Level: "error"